"""add BaseModel fields is_deleted updated_at encrypt linkedin token publish fields

Revision ID: 5dc4c939d477
Revises: 0a8df715e8fb
Create Date: 2026-03-08 18:30:01.433778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc4c939d477'
down_revision = '0a8df715e8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted to add server_default for existing rows ###
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_post_urn', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('publish_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               server_default='draft')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               server_default=sa.func.now())
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               server_default=sa.func.now())
        batch_op.create_index(batch_op.f('ix_drafts_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_drafts_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_drafts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_drafts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('linkedin_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_used_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               server_default=sa.func.now())
        batch_op.create_index(batch_op.f('ix_linkedin_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_linkedin_tokens_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_linkedin_tokens_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               server_default=sa.func.now())
        batch_op.create_index(batch_op.f('ix_usage_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               server_default='free')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               server_default=sa.func.now())
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_plan'), ['plan'], unique=False)
        batch_op.create_unique_constraint('uq_users_stripe_customer_id', ['stripe_customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_plan'))
        batch_op.drop_index(batch_op.f('ix_users_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('avatar_url',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_action'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('extra_data')

    with op.batch_alter_table('linkedin_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_linkedin_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_linkedin_tokens_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_linkedin_tokens_expires_at'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('access_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('last_used_at')

    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drafts_user_id'))
        batch_op.drop_index(batch_op.f('ix_drafts_status'))
        batch_op.drop_index(batch_op.f('ix_drafts_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_drafts_is_deleted'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('publish_error')
        batch_op.drop_column('linkedin_post_urn')

    # ### end Alembic commands ###
